CREATE TABLE if not exists category
(
    id   integer primary key NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(30)         unique NOT NULL,
    image varchar NOT NULL
);

CREATE TABLE if not exists item
(
    id         integer primary key NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(50)         NOT NULL,
    price      float8              NOT NULL,
    quantity integer not null,
    date       date                NOT NULL default current_date,
    likes integer NOT NULL default 0,
    categoryId integer             NOT NULL references category (id) on delete cascade on update cascade
);

/* Table 'User' */
CREATE TABLE if not exists usuario
(
    id    varchar primary key NOT NULL unique,
    email varchar unique            NOT NULL,
    name  varchar             NOT NULL,
    image varchar
);

/* Table 'UserItem' */
CREATE TABLE if not exists usuarioItem
(
    id     integer primary key NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    itemId integer             NOT NULL references item (id) on delete cascade on update cascade,
    userId varchar             NOT NULL references usuario (id) on delete cascade on update cascade,
    status varchar             NOT NULL
);

CREATE TABLE if not exists usuarioCart
(
    id     integer primary key NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    itemId integer             NOT NULL references item (id) on delete cascade on update cascade,
    userId varchar             NOT NULL references usuario (id) on delete cascade on update cascade
);

CREATE TABLE if not exists usuarioItemLike
(
    id     integer primary key NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    itemId integer             NOT NULL references item (id) on delete cascade on update cascade,
    userId varchar             NOT NULL references usuario (id) on delete cascade on update cascade
);


CREATE TABLE if not exists itemimage(
      itemid integer NOT NULL references item (id) on delete cascade on update cascade,
      image text NOT NULL
);